gcp:
    location: "us"
    region: "us-west1"
    sandbox_project_id: "sandbox-382905"
    prod_project_id: "production-382518"
    prod_db: "app_db_public"
gcs:
    bucket: "judie-exploration-us-west1"
    base: "rowan"
    analytics: "data_stats"
    transcripts: "transcripts"
    user_stats: "user_stats"
tables:
    users_table: "users"
    messages_table: "messages"
    chats_table: "chats"
sql:
    users_query: "sql/user_stats.sql"
    all_transcripts: "sql/all_transcripts.sql"
    select_transcripts: "sql/select_transcripts.sql"
