version: "3.8"
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: none
    ports:
      - 5438:5432
    networks:
      - dev
    volumes:
      - judie-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server --requirepass redis
    volumes:
      - judie-redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    networks:
      - dev
  app-service:
    networks:
      - dev
    privileged: true
    volumes:
      - ./app-service:/app
    working_dir: /app
    build:
      context: ./app-service
      dockerfile: ./Dockerfile.local
    ports:
      - 8080:8080
    environment:
      ENV: development
      SERVER_PORT: 8080
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB_NAME: postgres
  inference-service:
    networks:
      - dev
    privileged: true
    volumes:
      - ./inference-service:/app
    working_dir: /app
    build:
      context: ./inference-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ENV: development
      SERVER_PORT: 8080
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB_NAME: postgres
networks:
  dev:
    driver: bridge
volumes:
  judie-postgres-data: {}
  judie-redis-data: {}
