name: Production web CD

on:
  push:
    branches:
      - production
    paths:
      - "services/web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "projects/467740700781/locations/global/workloadIdentityPools/pool-gha/providers/gha-provider"
          service_account: "terraform@production-382518.iam.gserviceaccount.com"
          access_token_lifetime: 600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/web
          push: true
          platform: linux/amd64
          tags: |
            us-west1-docker.pkg.dev/production-382518/web/web:${{ github.sha }}
            us-west1-docker.pkg.dev/production-382518/web/web:latest
          build-args: |
            NEXT_PUBLIC_API_URI=https://app-service.judie.io
            NEXT_PUBLIC_NODE_ENV=production
            NEXT_PUBLIC_SEGMENT_WRITE_KEY=${{ secrets.SEGMENT_WRITE_KEY }}
            NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ secrets.GA_MEASUREMENT_ID }}
            NEXT_PUBLIC_UPFLUENCE_SCRIPT_ID=${{ secrets.UPFLUENCE_SCRIPT_ID }}

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          image: us-west1-docker.pkg.dev/production-382518/web/web:${{ github.sha }}
          service: web
          region: us-west1
          platform: managed
          project: production-382518
          allow-unauthenticated: true
