name: Deploy web

on:
  push:
    branches:
    - sandbox
    paths:
    - "services/web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/617839389948/locations/global/workloadIdentityPools/github-actions/providers/gha-provider'
          service_account: 'terraform@sandbox-382905.iam.gserviceaccount.com'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/web
          push: true
          tags: gcr.io/sandbox-382905/web:${{ github.sha }}
          # Need to pass in build args for Next.js build happening - no runtime ENV vars in Next.js
          build-args: |
            NEXT_PUBLIC_API_URI=https://app-service.sandbox.judie.io
            NEXT_PUBLIC_NODE_ENV=sandbox

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: gcr.io/sandbox-382905/web:${{ github.sha }}
          service: web
          region: us-west1
          platform: managed
          project: sandbox-382905
          allow-unauthenticated: true